### ISSUE TITLE
production build not using babelrc

### ISSUE THREAD

**Issue by SampsonCrowley** [Sawtaytoes/Ghadyani-Framework-Webpack-React-Redux#4]
```
ERROR in ./src/components/header/header.jsx
Module build failed: SyntaxError: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:
 
npm install babel-plugin-transform-decorators-legacy --save-dev
 
and add the following line to your .babelrc file:
 
{
  "plugins": ["transform-decorators-legacy"]
}
 
The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
```

but my babelrc has: 
```json
{
  "plugins": [
    "transform-runtime",
    "transform-class-properties",
    "react-hot-loader/babel",
    "transform-decorators-legacy"
  ],
  "presets": [
    "latest",
    "stage-0",
    "react",
  ],
}
```

**Comment by SampsonCrowley** [comment]
this is not an issue in dev mode and i added `require('babel-core/register')({ presets: ['latest'] })` to the top of `server-prod.js`

**Comment by Sawtaytoes** [comment]
Hmm... That's strange. So you're saying if you add decorators to `.babelrc`, it doesn't work properly for production builds, but it works for development.

You'll need to modify this to work with decorators: `require('babel-core/register')({ presets: ['latest'] }) `

Like so:
```js
require('babel-core/register')({
    plugins: ['transform-decorators-legacy'],
    presets: ['latest'],
}) 
```

Normally `.babelrc` is used, but here, it's been customized because `.babelrc` in this project is designed for client-side only. An even better fix is to make a server-side `.babelrc-server` that gets required in for this config so it can be shared in both server-dev and server-prod.

**Comment by SampsonCrowley** [comment]
where would I import babelrc-server?

**Comment by SampsonCrowley** [comment]
where is babelrc currently being imported for client side?

**Comment by SampsonCrowley** [comment]
the part I don't understand is how it is working in dev mode. I don't see anything that would make babel use the babelrc in dev but not in production

**Comment by SampsonCrowley** [comment]
the file this is crashing on is a client file btw

**Comment by SampsonCrowley** [comment]
fixed by adding: `'babel-loader?plugins[]=transform-decorators-legacy,presets[]=latest,presets[]=stage-0,presets[]=react'` to webpack.config.server.prod.js
